module vagent

import x.json2

// witness.v — proving the boundary actually ran.
//
// Every module here produces a guarantee, and every one of them rests on the
// same unexamined assumption: that the enforcement code ran at all, on every
// call, and that its record is complete.
//
// That assumption is exactly what an operator cannot check. The reports are
// generated by the same process they describe. A blocked count appears
// because the Covenant appended it; if a call had slipped past the gate
// entirely, nothing would appear, and an empty violation list looks
// identical to a perfect record. So
//
//     "no violations were recorded"
//     "no violations occurred"
//     "the check never ran"
//
// are three different states that all print as silence.
//
// Enforcement decisions therefore go into their own hash chain, separate
// from the fact that the kernel already seals events. Each decision carries
// the digest of the one before it, which buys two properties the per-event
// seals do not have:
//
//   * COMPLETE. Every gated call appends a decision — allowed as well as
//     refused. A call with no decision is a GAP, and verify() finds gaps by
//     comparing the witnessed calls against the tool calls in the log.
//   * TAMPER-EVIDENT. Removing or editing a decision breaks every link
//     after it. You cannot delete the one refusal that embarrasses you
//     without invalidating the rest, and verify() names the index where the
//     break begins.
//
// WHAT IT DOES NOT PROVE. The chain is only as trustworthy as the storage it
// lives in: a process that can rewrite the whole log can rewrite the whole
// chain, recomputing every link. What it defeats is SELECTIVE edits, which
// is the realistic failure — a dropped record, a flipped verdict, a deleted
// refusal. Anchoring the head digest somewhere this process cannot reach
// closes the rest, and head() is what you would anchor.

pub const verdict_allowed = 'allowed'
pub const verdict_refused = 'refused'
pub const witness_genesis = '0'.repeat(64)

pub struct Decision {
pub:
	index   int
	prev    string
	tool    string
	verdict string
	clauses []string
	ts      f64
	digest  string
}

// payload is the bytes this link commits to — canonical and key-sorted, so
// the same decision always hashes identically.
pub fn (d &Decision) payload() string {
	return canonical(json2.Any({
		'index':   json2.Any(d.index)
		'prev':    json2.Any(d.prev)
		'tool':    json2.Any(d.tool)
		'verdict': json2.Any(d.verdict)
		'clauses': json2.Any(d.clauses.map(json2.Any(it)))
		'ts':      json2.Any(round_to(d.ts, 6))
	}))
}

pub fn (d &Decision) recompute() string {
	return hash(d.payload())
}

pub fn (d &Decision) to_json() map[string]json2.Any {
	return {
		'index':   json2.Any(d.index)
		'prev':    json2.Any(d.prev)
		'tool':    json2.Any(d.tool)
		'verdict': json2.Any(d.verdict)
		'clauses': json2.Any(d.clauses.map(json2.Any(it)))
		'ts':      json2.Any(d.ts)
		'digest':  json2.Any(d.digest)
	}
}

pub fn decision_from_json(d map[string]json2.Any) Decision {
	return Decision{
		index:   jint(d, 'index')
		prev:    if p := d['prev'] { p.str() } else { witness_genesis }
		tool:    jstr(d, 'tool')
		verdict: jstr(d, 'verdict')
		clauses: jstrs(d, 'clauses')
		ts:      jf64(d, 'ts')
		digest:  jstr(d, 'digest')
	}
}

pub struct Audit {
pub mut:
	length    int
	intact    bool = true
	broken_at int = -1
	gaps      []string
	allowed   int
	refused   int
	problems  []string
}

pub fn (a &Audit) ok() bool {
	return a.intact && a.gaps.len == 0 && a.problems.len == 0
}

pub fn (a &Audit) describe() string {
	if a.length == 0 {
		return 'witness: no decisions recorded — the boundary has not run, or nothing has been gated yet'
	}
	head := 'witness: ${a.length} decision(s) · ${a.refused} refused / ${a.allowed} allowed'
	if a.ok() {
		return head + '\n  chain intact, every gated call accounted for'
	}
	mut lines := [head]
	if !a.intact {
		lines << '  !! chain broken at index ${a.broken_at} — a decision was edited or removed'
	}
	for g in a.gaps {
		lines << '  !! no decision witnessed for: ${g}'
	}
	for p in a.problems {
		lines << '  !! ${p}'
	}
	return lines.join('\n')
}

@[heap]
pub struct Witness {
pub mut:
	log   &EventLog
	chain []Decision
}

pub fn new_witness(log &EventLog) &Witness {
	return &Witness{
		log: unsafe { log }
	}
}

// -- appending ---------------------------------------------------------------

// head is the digest to anchor externally: everything the chain has seen is
// committed to by this one value.
pub fn (w &Witness) head() string {
	return if w.chain.len > 0 { w.chain.last().digest } else { witness_genesis }
}

// record witnesses one decision — including an allowance.
//
// Recording allowances is the point. A chain of refusals proves only that
// some refusals happened; a chain of EVERY decision proves that no call went
// unjudged, which is the stronger and more useful claim.
pub fn (mut w Witness) record(tool string, verdict string, clauses []string) Decision {
	unsealed := Decision{
		index:   w.chain.len
		prev:    w.head()
		tool:    tool
		verdict: verdict
		clauses: clauses.clone()
		ts:      now_ts()
	}
	d := Decision{
		index:   unsealed.index
		prev:    unsealed.prev
		tool:    unsealed.tool
		verdict: unsealed.verdict
		clauses: unsealed.clauses
		ts:      unsealed.ts
		digest:  unsealed.recompute()
	}
	w.chain << d
	w.log.append('witness.decision', d.to_json(), AppendOpts{ actor: 'kernel' })
	return d
}

pub fn (mut w Witness) allow(tool string) Decision {
	return w.record(tool, verdict_allowed, [])
}

pub fn (mut w Witness) refuse(tool string, clauses []string) Decision {
	return w.record(tool, verdict_refused, clauses)
}

// -- verification ------------------------------------------------------------

// verify checks the chain end to end.
//
// `expect_tools` is the list of calls that SHOULD have been judged — the
// tool.call events in the log. Comparing it against the chain is what turns
// silence into a finding.
pub fn (w &Witness) verify(expect_tools []string, has_expect bool) Audit {
	mut a := Audit{
		length: w.chain.len
	}
	mut prev := witness_genesis
	for i, d in w.chain {
		if d.index != i || d.prev != prev {
			a.intact = false
			a.broken_at = i
			break
		}
		if d.digest != d.recompute() {
			a.intact = false
			a.broken_at = i
			a.problems << 'decision ${i} does not match its digest'
			break
		}
		prev = d.digest
		match d.verdict {
			verdict_refused { a.refused++ }
			verdict_allowed { a.allowed++ }
			else { a.problems << "decision ${i} has an unknown verdict '${d.verdict}'" }
		}
	}

	if has_expect && a.intact {
		mut witnessed := map[string]int{}
		for d in w.chain {
			witnessed[d.tool] = witnessed[d.tool] + 1
		}
		for tool in expect_tools {
			if witnessed[tool] > 0 {
				witnessed[tool] = witnessed[tool] - 1
			} else {
				a.gaps << tool
			}
		}
	}
	return a
}

// -- portability -------------------------------------------------------------

// export is the chain, for checking somewhere this process cannot reach.
pub fn (w &Witness) export() []map[string]json2.Any {
	return w.chain.map(it.to_json())
}

// witness_check verifies an exported chain with no access to this process.
//
// It is a free function on purpose: verification must not need the object
// that produced the chain, or it would be the same process vouching for
// itself again.
pub fn witness_check(exported []map[string]json2.Any) Audit {
	mut a := Audit{
		length: exported.len
	}
	mut prev := witness_genesis
	for i, raw in exported {
		d := decision_from_json(raw)
		if d.index != i || d.prev != prev || d.digest != d.recompute() {
			a.intact = false
			a.broken_at = i
			break
		}
		prev = d.digest
		if d.verdict == verdict_refused {
			a.refused++
		} else {
			a.allowed++
		}
	}
	return a
}

// rebuild reloads the chain from the sealed log, after a restart.
pub fn (mut w Witness) rebuild() int {
	mut chain := []Decision{}
	for ev in w.log.events(w.log.branch) {
		if ev.typ == 'witness.decision' {
			chain << decision_from_json(ev.data)
		}
	}
	w.chain = chain
	return w.chain.len
}

pub fn (w &Witness) report(expect_tools []string, has_expect bool) string {
	head := w.head()
	short := if head.len >= 16 { head[..16] } else { head }
	return w.verify(expect_tools, has_expect).describe() + '\n  head: ${short}'
}
